version: '3'
services:
  agile-rabbit-mq:
    image: rabbitmq:3-management
    hostname: qrms-rabbit-mq
    ports:
      - 5672:5672
      - '8888:15672'
  agile-rabbit-mongo:
    image: mongo
    ports:
      - '27017:27017'