version: '3'
services:
  agile-rabbit-mq:
    image: rabbitmq:3-management
    hostname: qrms-rabbit-mq
    ports:
      - 5672:5672
      - '8888:15672'
  agile-rabbit-mongo:
    image: mongo
    ports:
      - '27017:27017'
  proxy:
    image: traefik
    ports:
      - '82:80'
      - '8080:8080'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - './config/traefik.toml:/etc/traefik/traefik.toml'
    network_mode: host
